"""drop nama_lengkap dari tabel admin

Revision ID: b55986c582ef
Revises: 
Create Date: 2025-11-17 22:10:03.618796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b55986c582ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('nama_lengkap')

    with op.batch_alter_table('rule_premise', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('rule_premise_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('rule_premise_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rule_set', ['id_ruleset'], ['id_ruleset'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'gejala', ['id_gejala'], ['id_gejala'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('rule_set', schema=None) as batch_op:
        batch_op.alter_column('cf_ruleset',
               existing_type=mysql.DECIMAL(precision=4, scale=2),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('rule_set_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'penyakit', ['id_penyakit'], ['id_penyakit'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_set', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rule_set_ibfk_1'), 'penyakit', ['id_penyakit'], ['id_penyakit'], ondelete='CASCADE')
        batch_op.alter_column('cf_ruleset',
               existing_type=sa.Float(precision=2),
               type_=mysql.DECIMAL(precision=4, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('rule_premise', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rule_premise_ibfk_2'), 'gejala', ['id_gejala'], ['id_gejala'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('rule_premise_ibfk_1'), 'rule_set', ['id_ruleset'], ['id_ruleset'], ondelete='CASCADE')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_lengkap', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
